
# Drummond checklist item text, for readable labels -- mirrors
# fullrun/quality-assessment/prompts/checklist_sections.json, inlined here so
# the app doesn't depend on fullrun/ being present alongside app/.
QA_SECTIONS <- list(
  list(id = "1", title = "Was a well-defined question posed in answerable form?", items = list(
    "1.1" = "Did the study examine both costs and effects of the service(s) or programme(s) over an appropriate time horizon?",
    "1.2" = "Did the study involve a comparison of alternatives?",
    "1.3" = "Was a perspective for the analysis stated and was the study placed in any particular decision-making context?",
    "1.4" = "Were the patient population and any relevant subgroups adequately defined?"
  )),
  list(id = "2", title = "Was a comprehensive description of the competing alternatives given?", items = list(
    "2.1" = "Were any relevant alternatives omitted?",
    "2.2" = "Was (should) a 'do nothing' alternative (be) considered?",
    "2.3" = "Were relevant alternatives identified for the patient subgroups?"
  )),
  list(id = "3", title = "Was the effectiveness of the programme or services established?", items = list(
    "3.1" = "Was this done through a randomized controlled clinical trial? If so, did the trial protocol reflect what would happen in regular practice?",
    "3.2" = "Were effectiveness data collected and summarized through a systematic overview of clinical studies? If so, were the search strategy and rules for inclusion or exclusion outlined?",
    "3.3" = "Were observational data or assumptions used to establish effectiveness? If so, were any potential biases recognized?"
  )),
  list(id = "4", title = "Were all the important and relevant costs and consequences for each alternative identified?", items = list(
    "4.1" = "Was the range wide enough for the research question at hand?",
    "4.2" = "Did it cover all relevant perspectives?",
    "4.3" = "Were capital costs, as well as operating costs, included?"
  )),
  list(id = "5", title = "Were costs and consequences measured accurately in appropriate physical units?", items = list(
    "5.1" = "Were the sources of resource utilization described and justified?",
    "5.2" = "Were any of the identified items omitted from measurement? If so, does this mean that they carried no weight in the subsequent analysis?",
    "5.3" = "Were there any special circumstances that made measurement difficult? Were these circumstances handled appropriately?"
  )),
  list(id = "6", title = "Were the cost and consequences valued credibly?", items = list(
    "6.1" = "Were the sources of all values clearly identified?",
    "6.2" = "Were market values employed for changes involving resources gained or depleted?",
    "6.3" = "Where market values were absent or did not reflect actual values, were adjustments made to approximate market values?",
    "6.4" = "Was the valuation of consequences appropriate for the question posed?"
  )),
  list(id = "7", title = "Were costs and consequences adjusted for differential timing?", items = list(
    "7.1" = "Were costs and consequences that occur in the future 'discounted' to their present values?",
    "7.2" = "Was any justification given for the discount rate(s) used?"
  )),
  list(id = "8", title = "Was an incremental analysis of costs and consequences of alternatives performed?", items = list(
    "8.1" = "Were the additional (incremental) costs generated by one alternative over another compared to the additional effects, benefits, or utilities generated?"
  )),
  list(id = "9", title = "Was allowance made for uncertainty in the estimates of costs and consequences?", items = list(
    "9.1" = "If patient-level data on costs or consequences were available, were appropriate statistical analyses performed?",
    "9.2" = "If a sensitivity analysis was employed, was justification provided for the form(s) used and the ranges or distributions of values?",
    "9.3" = "Were the conclusions of the study sensitive to the uncertainty in the results?",
    "9.4" = "Was heterogeneity in the patient population recognized, for example by presenting study results for relevant subgroups?"
  )),
  list(id = "10", title = "Did the presentation and discussion of study results include all issues of concern to users?", items = list(
    "10.1" = "Were the conclusions of the analysis based on some overall index or ratio of costs to consequences? If so, was the index interpreted intelligently or in a mechanistic fashion?",
    "10.2" = "Were the results compared with those of others who have investigated the same question?",
    "10.3" = "Did the study discuss the generalizability of the results to other settings and patient/client groups?",
    "10.4" = "Did the study allude to, or take account of, other important factors in the choice or decision under consideration?",
    "10.5" = "Did the study discuss issues of implementation, such as feasibility of adopting the 'preferred' programme?",
    "10.6" = "Were the implications of uncertainty for decision-making, including the need for future research, explored?"
  ))
)

QA_KEYS <- c(
  "1.1", "1.2", "1.3", "1.4", "2.1", "2.2", "2.3", "3.1", "3.2", "3.3",
  "4.1", "4.2", "4.3", "5.1", "5.2", "5.3", "6.1", "6.2", "6.3", "6.4",
  "7.1", "7.2", "8.1", "9.1", "9.2", "9.3", "9.4", "10.1", "10.2", "10.3",
  "10.4", "10.5", "10.6"
)

QA_SECTION_KEYS <- unlist(lapply(QA_SECTIONS, function(s) names(s$items)), use.names = FALSE)

stopifnot(identical(sort(QA_SECTION_KEYS), sort(QA_KEYS)))  # catches QA_SECTIONS/QA_KEYS drifting apart

stopifnot(
  identical(sort(QA_SECTION_KEYS), sort(QA_KEYS))
)

VERDICT_CHOICES <- c("Yes", "No", "Unclear", "Not applicable")

# Per fullrun/quality-assessment/prompts/quality_assessment_prompt.md: "Not
# applicable" is only ever a valid verdict for these 14 sub-items (matches
# fullrun/RUNBOOK.md's "14 named N/A-eligible items"). The other 19 must be
# Yes/No/Unclear -- offering "Not applicable" there would let a reviewer pick
# an answer the checklist itself says is wrong.
QA_NA_ELIGIBLE <- c(
  "2.2", "2.3", "3.1", "3.2", "3.3", "4.3", "5.3", "6.2", "6.3",
  "7.1", "7.2", "9.1", "9.2", "9.3"
)
qa_verdict_choices <- function(key) if (key %in% QA_NA_ELIGIBLE) VERDICT_CHOICES else setdiff(VERDICT_CHOICES, "Not applicable")



qa_id <- function(key) gsub("\\.", "_", key)